apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
      # Tells Istio (Phase 5) this is HTTP without protocol sniffing.
      appProtocol: http
